server:
  port: 8888

info:
  description: Spring Cloud Config Server
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://archimedes1:8761/eureka/,http://archimedes2:8762/eureka/
    healthcheck:
      enabled: true
    
spring:
  application:
    name: configserver
  cloud:
    bus: 
      trace:
        enabled: true
    config:
      server:
        git:
         uri: https://github.com/codependent/storyteller-microservices-config
#          uri: file:///C:/Users/jinga4x/git/storyteller-microservices-config/
#        native:
#          searchLocations: file:///C:/Users/jinga4x/git/storyteller-microservices-config/
          
#  profiles:
#    active: native